name: CI

on:
    push:
        branches: '*'
    pull_request:
        branches: '*'

jobs:
  crystal:
    runs-on: ubuntu-latest
    name: Crystal Mine
    container:
      image: crystallang/crystal

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        crystal -v
        shards install

    - name: Run ameba linter
      run: |
        ./bin/ameba


